add print env variables

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -37,56 +37,62 @@ jobs:
       with:
         terraform_version: $TF_VERSION
 
-    - name: Install Terragrunt
+    - name: Print GitHub Actions env variables
       run: |
-       curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TG_VERSION/terragrunt_linux_amd64
-       chmod +x terragrunt
-       sudo mv terragrunt /bin
+        echo "${{ env.GITHUB_HEAD_REF }}"
+        echo "${{ env.GITHUB_REF }}"
+        echo "${{ env.GITHUB_REF_NAME }}"
+
+    # - name: Install Terragrunt
+    #   run: |
+    #    curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TG_VERSION/terragrunt_linux_amd64
+    #    chmod +x terragrunt
+    #    sudo mv terragrunt /bin
       
-    - name: Install tfsec
-      run: |
-       wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/$TFSEC_VERSION/tfsec-linux-amd64
-       chmod +x ./tfsec
-       mv ./tfsec /usr/local/bin/tfsec
+    # - name: Install tfsec
+    #   run: |
+    #    wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/$TFSEC_VERSION/tfsec-linux-amd64
+    #    chmod +x ./tfsec
+    #    mv ./tfsec /usr/local/bin/tfsec
 
-    - name: Verify Terragrunt version
-      run: terragrunt --version
+    # - name: Verify Terragrunt version
+    #   run: terragrunt --version
       
-    - name: Verify Terraform version
-      run: terraform --version
+    # - name: Verify Terraform version
+    #   run: terraform --version
       
-    - name: Verify awscli version
-      run: aws --version
+    # - name: Verify awscli version
+    #   run: aws --version
 
-    - name: tfsec report
-      run: |
-         tfsec $CODE_DIR --format junit --out tfsec-junit.xml
-      shell: bash
-      continue-on-error: true
+    # - name: tfsec report
+    #   run: |
+    #      tfsec $CODE_DIR --format junit --out tfsec-junit.xml
+    #   shell: bash
+    #   continue-on-error: true
 
-    - name: Terragrunt Format
-      id: fmt
-      run: terragrunt fmt -check -recursive --terragrunt-working-dir $CODE_DIR -diff
-      continue-on-error: false
+    # - name: Terragrunt Format
+    #   id: fmt
+    #   run: terragrunt fmt -check -recursive --terragrunt-working-dir $CODE_DIR -diff
+    #   continue-on-error: false
 
-    - name: Terragrunt Validate
-      id: validate
-      run: terragrunt validate --terragrunt-working-dir $CODE_DIR 
-      continue-on-error: true
+    # - name: Terragrunt Validate
+    #   id: validate
+    #   run: terragrunt validate --terragrunt-working-dir $CODE_DIR 
+    #   continue-on-error: true
 
-    - name: Post Validate
-      if: always() && github.ref != 'refs/heads/master' && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure')
-      uses: robburger/terraform-pr-commenter@v1
-      with:
-        commenter_type: validate
-        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
-        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
+    # - name: Post Validate
+    #   if: always() && github.ref != 'refs/heads/master' && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure')
+    #   uses: robburger/terraform-pr-commenter@v1
+    #   with:
+    #     commenter_type: validate
+    #     commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
+    #     commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
 
-    - name: Post TfSec Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    
-      with:
-        fail-on-error: false
-        name: TfSec Tests            # Name of the check run which will be created
-        path: tfsec-junit.xml        # Path to test results
-        reporter: java-junit         # Format of test results
+    # - name: Post TfSec Report
+    #   uses: dorny/test-reporter@v1
+    #   if: success() || failure()    
+    #   with:
+    #     fail-on-error: false
+    #     name: TfSec Tests            # Name of the check run which will be created
+    #     path: tfsec-junit.xml        # Path to test results
+    #     reporter: java-junit         # Format of test results
